version: "3.8"

services:
  backend:
    build: .
    container_name: chat-central
    restart: always
    tty: true
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=mongodb://crossover.proxy.rlwy.net:52597
      - REDIS_URI=redis://maglev.proxy.rlwy.net:17929
      - JWT_SECRET_KEY=ba7c3a58d4f8451b938f8a89d2e6a7cdd63cdbdba293a0d59d13c8a55f27b1cb
    networks:
      - chat-central-network
    labels:
      com.example.description: "Container do Backend Chat Central"

networks:
  chat-central-network:
